### ISSUE TITLE
Fixes for Chapter 5 for v4

### ISSUE THREAD

**Issue by newtonlabs** [climboid/d3jsMaps#3]
* Chapter 5: examples 2, 4, 5, and 6

**Comment by newtonlabs** [comment]
Fixed Chapter 5, example 5 in PR https://github.com/climboid/d3jsMaps/pull/4

**Comment by newtonlabs** [comment]
@climboid I think example 4 is ok.. It is just the picture of the globe correct?

**Comment by climboid** [comment]
not totally sure Thomas, need to check the portal for the image taken
